name: groshidze-blog
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
            yarn install
            ls
            cd blog/blog
            ls
            yarn run build
