name: groshidze-blog
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
            yarn install
            echo "View directory"
            ls
            echo "start build"
            yarn run build
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        run: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
            chmod 700 ~/.ssh/id_ed25519
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
            ssh-keyscan -t rsa 158.160.30.152 > ~/.ssh/known_hosts
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
            chmod 644 ~/.ssh/known_hosts
            ls
            echo "Switching to branch main"
            git checkout main
            echo "Init deps..."
            yarn install
            echo "Building app..."
            yarn build
            echo "Deploying files to server..."
            scp -r dist/* grosh@158.160.30.152:/var/www/groshidze/dist
            echo "Done!"
