name: groshidze-blog
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blog
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
            yarn install
            yarn build
